services:
  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${SPRING_R2DBC_USERNAME}
      MYSQL_PASSWORD: ${SPRING_R2DBC_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      # Usamos root para el ping para evitar problemas de permisos durante el arranque
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$${SPRING_R2DBC_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: spring_app
    environment:
      SPRING_R2DBC_URL: ${SPRING_R2DBC_URL}
      SPRING_R2DBC_USERNAME: ${SPRING_R2DBC_USERNAME}
      SPRING_R2DBC_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
